// Generates pre-composited map marker PNGs + a markerImages.ts lookup.
// Marker = operator logo + a category-colored ring (ultra/dc/hybrid/ac) + a pill of
// per-charger status dots. Static images via Marker `source` render reliably (a
// React-child <Image> is missed by the Yandex bitmap snapshot). Run from apps/mobile with
// NODE_PATH pointed at the repo-root node_modules (for sharp):
//   NODE_PATH=/d/Projects/VoltAI/node_modules node scripts/gen-markers.cjs
const sharp = require('sharp');
const fs = require('fs');
const path = require('path');

const OUT_DIR = path.join(process.cwd(), 'assets', 'operators', 'markers');
const TS_FILE = path.join(process.cwd(), 'lib', 'markerImages.ts');

const OPS = ['tokbor', 'spectre-energy', 'k-watt', 'generic'];
const CATS = { ultra: '#A855F7', dc: '#3FA9F5', hybrid: '#14D6C4', ac: '#9AA3AD' };
// status dots: available / in-use / offline (unknown folds into offline grey)
const DOT = { A: '#2FE28A', I: '#F7B84B', O: '#8A9099' };
const LETTERS = ['A', 'I', 'O'];
const MAX_DOTS = 4;

const W = 148;
const H = 176;
const PIN = { x: 22, y: 6, w: 104, h: 104, rx: 30 };
const LOGO = 82;
const LOGO_CX = PIN.x + PIN.w / 2;
const LOGO_CY = PIN.y + PIN.h / 2;

function multisets(size) {
  const res = [];
  (function rec(start, cur) {
    if (cur.length === size) { res.push(cur.join('')); return; }
    for (let i = start; i < LETTERS.length; i++) rec(i, [...cur, LETTERS[i]]);
  })(0, []);
  return res;
}
const PATTERNS = [];
for (let s = 1; s <= MAX_DOTS; s++) PATTERNS.push(...multisets(s));

function frameSvg(catColor, pattern) {
  const n = pattern.length;
  const dotR = 6, gap = 6, pillH = 26;
  const contentW = n * (dotR * 2) + (n - 1) * gap;
  const pillW = contentW + 20;
  const pillX = (W - pillW) / 2;
  const pillY = PIN.y + PIN.h + 8;
  let dots = '';
  let dx = pillX + 10 + dotR;
  const dy = pillY + pillH / 2;
  for (const ch of pattern) {
    dots += `<circle cx="${dx}" cy="${dy}" r="${dotR}" fill="${DOT[ch]}" stroke="rgba(255,255,255,0.5)" stroke-width="1"/>`;
    dx += dotR * 2 + gap;
  }
  return `<svg width="${W}" height="${H}" xmlns="http://www.w3.org/2000/svg">
      <rect x="${PIN.x}" y="${PIN.y}" width="${PIN.w}" height="${PIN.h}" rx="${PIN.rx}" fill="#FFFFFF" stroke="${catColor}" stroke-width="9"/>
      <rect x="${pillX}" y="${pillY}" width="${pillW}" height="${pillH}" rx="${pillH / 2}" fill="#0F1114"/>
      ${dots}
    </svg>`;
}

(async () => {
  fs.mkdirSync(OUT_DIR, { recursive: true });
  // clear old
  for (const f of fs.readdirSync(OUT_DIR)) if (f.endsWith('.png')) fs.unlinkSync(path.join(OUT_DIR, f));

  const logos = {};
  for (const op of ['tokbor', 'spectre-energy', 'k-watt']) {
    logos[op] = await sharp(path.join('assets', 'operators', op + '.png'))
      .resize(LOGO, LOGO, { fit: 'contain', background: { r: 0, g: 0, b: 0, alpha: 0 } })
      .toBuffer();
  }

  const entries = [];
  for (const op of OPS) {
    for (const [cat, catColor] of Object.entries(CATS)) {
      for (const pattern of PATTERNS) {
        const file = `${op}-${cat}-${pattern}.png`;
        let svg = frameSvg(catColor, pattern);
        if (op === 'generic') {
          svg = svg.replace('</svg>', `<path d="M80 26 L54 66 L72 66 L64 96 L94 52 L76 52 Z" fill="#1AA63F"/></svg>`);
        }
        let img = sharp(Buffer.from(svg));
        if (op !== 'generic') {
          img = img.composite([{ input: logos[op], left: Math.round(LOGO_CX - LOGO / 2), top: Math.round(LOGO_CY - LOGO / 2) }]);
        }
        await img.png().toFile(path.join(OUT_DIR, file));
        entries.push(`  '${op}-${cat}-${pattern}': require('../assets/operators/markers/${file}'),`);
      }
    }
  }

  const ts = `import type { ImageSourcePropType } from 'react-native';
import type { ChargerCategory, StationStatus } from '@/types/stations';

/**
 * AUTO-GENERATED by scripts/gen-markers.cjs. Pre-composited map markers: operator logo +
 * category-colored ring (ultra/dc/hybrid/ac) + one status dot per charger. Static images via
 * the Marker \`source\` prop render reliably (a React-child <Image> is missed by the Yandex
 * bitmap snapshot). Regenerate after changing logos, categories, or the design.
 */
const MARKERS: Record<string, ImageSourcePropType> = {
${entries.join('\n')}
};

const LETTER: Record<StationStatus, string> = {
  available: 'A',
  in_use: 'I',
  offline: 'O',
  unknown: 'O',
};
const ORDER = 'AIO';
const MAX_DOTS = ${MAX_DOTS};

function patternOf(statuses: StationStatus[]): string {
  const letters = (statuses.length ? statuses : (['unknown'] as StationStatus[]))
    .map((s) => LETTER[s] ?? 'O')
    .sort((a, b) => ORDER.indexOf(a) - ORDER.indexOf(b))
    .slice(0, MAX_DOTS);
  return letters.join('');
}

export function markerImage(
  operatorId: string | undefined,
  category: ChargerCategory | undefined,
  statuses: StationStatus[],
): ImageSourcePropType {
  const pattern = patternOf(statuses);
  const cat: ChargerCategory = category ?? 'dc';
  return (
    MARKERS[\`\${operatorId}-\${cat}-\${pattern}\`] ??
    MARKERS[\`generic-\${cat}-\${pattern}\`] ??
    MARKERS['generic-dc-O']
  );
}
`;
  fs.writeFileSync(TS_FILE, ts);
  console.log(`generated ${OPS.length * Object.keys(CATS).length * PATTERNS.length} markers (${PATTERNS.length} patterns × ${Object.keys(CATS).length} cats × ${OPS.length} ops)`);
})();
