name: Scrape Spectre Energy

on:
  schedule:
    - cron: "15 3 1 * *"
  workflow_dispatch:

jobs:
  call:
    uses: ./.github/workflows/scrape-app.yml
    with:
      app_name: spectre-energy
    secrets: inherit
